services:
  backend_core:
    build:
      context: ./backend_core
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend_core/env/.env
    depends_on:
      - backend_core_db
      - frontend
    restart: on-failure
    ports:
      - 8000:8000
    networks:
        - backend_core_db_network
        - frontend_backend_network 
    volumes:
      - ./backend_core:/app

  backend_core_db:
    image: postgres:14-alpine
    volumes:
      - backend_core_db_volume:/var/lib/postgresql/data
    env_file:
      - ./backend_core/env/.env
    ports:
      - 5432:5432
    networks:
      - backend_core_db_network
  frontend:
    build:
      context: ./frontend 
      dockerfile: dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    networks:
      - frontend_backend_network
volumes:
  backend_core_db_volume:
  db_volume:
networks:
  backend_core_db_network:
    driver: bridge
  frontend_backend_network:
    driver: bridge