# Generated by Django 4.2.4 on 2024-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='solution_similar',
            field=models.ManyToManyField(blank=True, to='exercises_app.exercise'),
        ),
    ]
