# Generated by Django 4.2.4 on 2024-01-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0002_alter_exercise_solution_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='solution_similar',
            field=models.ManyToManyField(blank=True, null=True, to='exercises_app.exercise'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
