# Generated by Django 4.2.4 on 2024-01-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0003_alter_exercise_solution_similar_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=False),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
