# Generated by Django 4.2.4 on 2024-08-08 08:51
import json
import os
from django.db import migrations

current_directory = os.path.dirname(__file__)
file_path = os.path.join(current_directory, 'sections_data.txt')


def read_json_from_file(file_path):
    try:
        with open(file_path, 'r') as file:
            data = json.load(file)
            return data
    except FileNotFoundError:
        print(f'File not found: {file_path}')
    except json.JSONDecodeError:
        print(f'Error decoding JSON from the file: {file_path}')


data = read_json_from_file(file_path)


def add_subsubsection_data(apps, schema_editor):
    Subsection = apps.get_model('exercises_app', 'Subsection')
    Subsubsection = apps.get_model('exercises_app', 'Subsubsection')
    for i in data:
        for j in i['Subsections']:
            subsection = Subsection.objects.get(name=j['name'])
            if 'Subsubsections' in j:
                for y in j['Subsubsections']:
                    name = y['name']
                    subsubsection = Subsubsection.objects.create(name=name, subsection=subsection)


class Migration(migrations.Migration):
    dependencies = [
        ('exercises_app', '0003_add_subsection_data'),
    ]

    operations = [
        migrations.RunPython(add_subsubsection_data),
    ]
