# Generated by Django 4.2.4 on 2024-01-19 21:30
import json
import os
from django.db import migrations
from django.utils.text import slugify


current_directory = os.path.dirname(__file__)
file_path = os.path.join(current_directory, 'data.txt')

def read_json_from_file(file_path):
    try:
        with open(file_path, 'r') as file:
            data = json.load(file)
            return data
    except FileNotFoundError:
        print(f'File not found: {file_path}')
    except json.JSONDecodeError:
        print(f'Error decoding JSON from the file: {file_path}')

data = read_json_from_file(file_path)

def add_section_data(apps, schema_editor):
    Section = apps.get_model('exercises_app', 'Section')
    for i in data:
        name = i['Section']
        slug = slugify(name)
        Section.objects.create(name=name, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_exercise_slug_section_slug_subsection_slug'),
    ]

    operations = [
        migrations.RunPython(add_section_data),
    ]
