# Generated by Django 4.2.4 on 2024-01-19 21:30

from django.db import migrations
from django.utils.text import slugify


def add_section_data(apps, schema_editor):
    Section = apps.get_model('exercises_app', 'Section')
    for i in range(1, 6):
        name = f'sec{i}'
        slug = slugify(name)
        Section.objects.create(name=name, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_exercise_slug_section_slug_subsection_slug'),
    ]

    operations = [
        migrations.RunPython(add_section_data),
    ]
