# Generated by Django 4.2.4 on 2024-01-19 22:26

from django.db import migrations
from django.utils.text import slugify


def add_subsection_data(apps, schema_editor):
    Subsection = apps.get_model('exercises_app', 'Subsection')
    Section = apps.get_model('exercises_app', 'Section')
    sections = Section.objects.all()

    for section in sections:
        for y in range (1, 6):
            name = f'subsec{section.pk}{y}'
            slug = slugify(name)
            Subsection.objects.create(name=name, section=section, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0005_add_section_data'),
    ]

    operations = [
        migrations.RunPython(add_subsection_data),
    ]
