# Generated by Django 5.1 on 2024-09-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0005_add_exercises_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
    ]
