# Generated by Django 4.2.4 on 2024-01-20 19:13
from random import randint

from django.db import migrations
from django.utils.text import slugify


def add_exercise_data(apps, schema_editor):
    Exercise = apps.get_model('exercises_app', 'Exercise')
    Subsection = apps.get_model('exercises_app', 'Subsection')
    subsections = Subsection.objects.all()

    for subsection in subsections:
        for y in range (1, 15):
            title = f'ex{y} for subsection {subsection.name}'
            description = f'descriptoin for exercise {title}'
            subsection = subsection
            difficult = y
            points = difficult * 2
            type = randint(1, 6)
            advanced_level = False if difficult < 7 else True
            slug = slugify(title)
            Exercise.objects.create(title=title, description=description, subsection=subsection, difficult=difficult,
                                    points=points, type=type, advanced_level=advanced_level, slug=slug)

class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0006_add_subsection_data'),
    ]

    operations = [
        migrations.RunPython(add_exercise_data),
    ]
