# Generated by Django 4.2.4 on 2024-01-20 19:38

from django.db import migrations


def add_answer_data(apps, schema_editor):
    Answer = apps.get_model('exercises_app', 'Answer')
    Exercise = apps.get_model('exercises_app', 'Exercise')
    exercises = Exercise.objects.all()

    for exercise in exercises:
        for y in range(1, 4):
            answer = exercise.pk + y
            correct = True if y == 1 else False
            Answer.objects.create(answer=answer, exercise=exercise, correct=correct)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0007_add_exercise_data'),
    ]

    operations = [
        migrations.RunPython(add_answer_data),
    ]
