# Generated by Django 4.2.4 on 2024-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0008_add_answer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exam',
            field=models.DateField(blank=True, null=True),
        ),
    ]
