# Generated by Django 4.2.4 on 2024-01-20 21:53
from django.contrib.auth.hashers import make_password
from django.db import migrations

def create_users(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    user1 = CustomUser(username='user1',  first_name='jan', last_name='kowalski', password=make_password('tajne'))
    user1.save()

    user2 = CustomUser(username='user2', first_name='jan', last_name='kowalski', password=make_password('tajne'))
    user2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_superuser'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
