# Generated by Django 4.2.4 on 2024-08-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('exercises_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='exercises_app.subsection'),
        ),
    ]
